spring.application.name=drivecare

server.port=12432

# DB 연결 정보
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://drivecare-db.c5zy8lqgwkgg.ap-northeast-2.rds.amazonaws.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=dkqksEp12#

# JPA & Hibernate 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# thymeleaf
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

# 정적 리소스 캐시 끄기
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# JWT
jwt.issuer=GITAUTO
app.jwt.secret=change-this-to-a-strong-base64-secret-or-256bit-key
app.jwt.access-token-expiration-seconds=900
app.jwt.refresh-token-expiration-seconds=1209600

# Gmail SMTP 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yeomju311@gmail.com
spring.mail.password=aabwszhrosmaslij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.from=yeomju311@gmail.com